import type { Meta, StoryObj } from '@storybook/react-vite';
import { fn } from 'storybook/test';
import { Alert } from './Alert';

const meta = {
  title: 'Components/Alert',
  component: Alert,
  parameters: { layout: 'padded' },
  tags: ['autodocs'],
  argTypes: {
    variant: { control: 'select', options: ['info', 'success', 'warning', 'error'] },
  },
  args: {
    title: 'Heads up',
    children: 'This is an alert generated by the component scaffolding tool.',
  },
} satisfies Meta<typeof Alert>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Info: Story = { args: { variant: 'info' } };
export const Success: Story = { args: { variant: 'success', title: 'Saved' } };
export const Warning: Story = { args: { variant: 'warning', title: 'Careful' } };
export const ErrorAlert: Story = { args: { variant: 'error', title: 'Something failed' } };
export const Dismissible: Story = { args: { onDismiss: fn() } };
